database_url="sqlite+aiosqlite:///src/db/database.db"


[bot]
ENV_BOT__TOKEN="12345678:ABCDEFG"
ENV_BOT__REQUIRED_CHATS=[-10012345678]
ENV_BOT__CHAT_LINK="https://t.me/YOUCHANNELLINK"
ENV_BOT__ADMIN_IDS=[1234567]